### ISSUE TITLE
Feature request: generate paths with the same DSL as they are defined

### ISSUE THREAD

**Issue by cabeza-de-termo** [hanami/router#108]
Currently the path for an action can be generated using a method that follows an implicit naming convention:

```ruby
routes.flowers
routes.flower id: 23
routes.new_flower
```

I think that might be a Rails reminiscence and find it unintuitive (that is manifested by the fact of needing to use a 'routes' command to see the named paths of the routes).
A more intuitive and direct approach might be to allow to generate the paths using the same DSL used to define the routes and that makes an explicit reference to the route action:

```ruby
get '/', to: 'welcome#index'

path_to 'welcome#index'
```

and for REST resources

```ruby
path_to 'flowers#index'
path_to 'flowers#show', id: 23
path_to 'flowers#edit', id: 23
# etc
```

and for nested resources

```ruby
#/users/1/favorites/2
path_to 'users::favorites#show', user_id: 1, id: 2
```

**Comment by jodosha** [comment]
@cabeza-de-termo Thanks for this suggestion, but I'm careful about the learning curve from Rails to Hanami. The less we change in these small details, the better is for newcomers.
