### ISSUE TITLE
Assigned but unused variables

### ISSUE THREAD

**Issue by justin-rhoades** [hanami/router#112]
When running tests in router and in Hanami, there are two warnings for assigned but unused variables. 

```/.rvm/gems/ruby-2.3.1/gems/http_router-0.11.2/lib/http_router/generator.rb:58: warning: assigned but unused variable - generator```
- This may be here for clarification purposes

and

```/.rvm/gems/ruby-2.3.1/gems/http_router-0.11.2/lib/http_router/route_helper.rb:99: warning: assigned but unused variable - params```
- Does not appear this variable is used at all in the method, could be removed?

Could definitely easily fix this if there is no reasoning for having the variables. Let me know!

**Comment by justin-rhoades** [comment]
Wow never mind. This was totally my bad, too early in the morning. Obviously this is an issue with the http_router gem -_-

**Comment by jodosha** [comment]
@justin-rhoades There is an open PR in `http_router` repository. Maybe you can upvote it. Thanks! https://github.com/joshbuddy/http_router/pull/47
