### ISSUE TITLE
Possible to have namespace with variable?

### ISSUE THREAD

**Issue by lasseebert** [hanami/router#114]
I have something like this:

```
Hanami::Router.new do
  get "/:id", id: /[0-9a-f]{32}/, to: "stuff#show"
  get "/:id/foos", id: /[0-9a-f]{32}/, to: "foos#index"
  get "/:id/bars", id: /[0-9a-f]{32}/, to: "bars#index"
  post "/:id/bars/", id: /[0-9a-f]{32}/, to: "bars#create"
end
```

Is it possible to somehow wrap all routes that starts with `/:id` into a block. Something like this:

```
Hanami::Router.new do
  namespace "/:id", id: /[0-9a-f]{32}/ do
    get "/", to: "stuff#show"
    get "/foos", to: "foos#index"
    get "/bars", to: "bars#index"
    post "/bars/", to: "bars#create"
  end
end
```

Thanks.

**Comment by jodosha** [comment]
@lasseebert I think this could be useful. Because you're directly involved with this enhancement, do you want to implement it? Thanks!

**Comment by jodosha** [comment]
I'm closing this as stale ticket. @lasseebert Feel free to reopen in case you still need it. Thanks!

**Comment by lasseebert** [comment]
Roger. I haven't had time to look at a solution yet. Will reopen if I find time to implement the feature ;)
