### ISSUE TITLE
Cannot control default reponse

### ISSUE THREAD

**Issue by davidpelaez** [hanami/router#119]
Hi.

We use Hanami Router for our internal JSON microservices. The default response cannot be controlled at the moment from I could get from the structure of https://github.com/hanami/router/blob/555f044ae79b367c0df92256a7d8c9154e71e478/lib/hanami/routing/endpoint_resolver.rb#L19

I tried monkey patching the class and even in that case it won't work. This is problematic in our use case because we can break clients very easily if we fail to deliver JSON responses in every case and also because we could use this to give a more detailed reply hinting a possibly correct route. 

We know this can be done with a wildcard get but if we use namespaces we have to put the wildcard at the end of all the routes and at the end of every namespace. Maybe this could be passed if the options when building a router, something like this:

```ruby
DefaultController = -> env {
   [ 404, {'Content-Type' => 'application/json'}, {error: :not_found}.to_json ]
}
Router = Hanami::Router.new(namespace: Controllers, default: DefaultController) # ....
```

Does this make sense? This is so far our only issue with Hanami Router, we like it a lot because if easy to begin with and simple to jump from if you already know Rails :)

**Comment by jodosha** [comment]
@davidpelaez Hi, this is undocumented because it comes from `http_router`, but you can already do exactly what you want via `default_app:` instead of `default`. See https://github.com/joshbuddy/http_router#usage
