### ISSUE TITLE
Mounting app after url parameter

### ISSUE THREAD

**Issue by TiteiKo** [hanami/router#121]
Hi all,

My title is terrible, sorry, can't figure out how to name it, but anyway, here's the thing:

I'm currently switching an app from rails to hanami. No changes in urls are possible.

Urls are of the following form: `(/:locale)/rest/of-the/url`, so, for example: `/en/admin/users` would go to Admin::Users::Index with locale en in its params.

What I've tried so far:
- using a fixed namespace to see if working on https://github.com/hanami/router/issues/114 could solve my problem. It seems like the mount just does not care about the namespace.
- `mount Admin::Application, at: '(/:locale)/admin'` which kinda almost work, except that all urls generated are screwed up with a nasty `(/:locale)` at the beginning (including asset urls)
- `mount Admin::Application.new(locale: 'fr'), at: '/fr/admin'` just to see if it was possible... let's just say it's not...

Questions:
- is this possible at the moment?
- if not, is this something that you'd be willing to be added to the router?
- and if so, do you have any general idea on how/where to start looking to implement it? (I've taken a look, I must confess I won't be able to do it without a bit of guidance)

**Comment by AlfonsoUceda** [comment]
Hi @titeiko have you tried `mount Admin::Application, at: '/:locale/admin'` without parenthesis? I am just writing without trying in the laptop because I'm not in front of it.

**Comment by TiteiKo** [comment]
@AlfonsoUceda Yep, same problem in urls generation with and without parenthesis. Generated urls looks like `/:locale/admin/users?locale=en`

**Comment by AlfonsoUceda** [comment]
I'll try to take a look this weekend @titeiko

**Comment by AlfonsoUceda** [comment]
Hi @TiteiKo I was researching the problem and it seems, there is a bug that you can't use `variables` in the container. So I have to see how I can fix it, sorry for the problem :(

**Comment by TiteiKo** [comment]
Hi @AlfonsoUceda 
Thanks for your time and the update! Glad I could uncover a bug, and no problem, Hanami's not supposed to be stable yet, and I'll still be able to work in the meantime, it's the last thing on my backlog for v1 ;)

**Comment by jodosha** [comment]
@TiteiKo @AlfonsoUceda Hi, this isn't a bug, it's just not possible to do so at the moment.

---

Because @TiteiKo is interested in this change, I suggest her to implement it.
At this point in time, it's beneficial that Hanami shareholders can write enhancements or features for real world apps.

**Comment by TiteiKo** [comment]
@jodosha I'd be glad to, and I've tried, before submitting this issue and again today...

@AlfonsoUceda Do you have any lead I could look into?

**Comment by AlfonsoUceda** [comment]
Hi @TiteiKo 

You can start [here](https://github.com/hanami/router/blob/master/lib/hanami/routing/http_router.rb#L80), the prefix in the container ends in that variable, when I was tackling this, one of my ideas was creating a class to handle that, replace `:variables` in that prefix with options passed to the path or url to generate.

**Comment by jodosha** [comment]
@TiteiKo Is this something still interesting for you to implement?

**Comment by TiteiKo** [comment]
@jodosha Not ATM, no. I've tried to do it, but without success. I'll use a rewrite rule on nginx to go from `/:locale/admin` to `/admin/:locale`
After looking at the code, I think it would make a lot of changes for a very specific need that would probably not occur on a fresh new project.

**Comment by jodosha** [comment]
@TiteiKo Thank you 😄
