### ISSUE TITLE
Nested resources with a dynamic part in the URL

### ISSUE THREAD

**Issue by choallin** [hanami/router#131]
I want to be able to call a url like this:
> http://server/post/relationships/comment  

and also
> http://server/post/relationships/tag  

to be able to add relations to my post. In my use case it is possible to handle both, the comment and the tag routes in one controller/action. So, it would be great to have this as a optional dynamic part of the router.
Something like this:
```ruby
resources :tags do
  resources :relationships,  url: "/relationships/:type"
end
```

**Comment by AlfonsoUceda** [comment]
@choallin sorry for the late response, it would be great is you want to make a PR ;)

**Comment by AlfonsoUceda** [comment]
Hi @choallin, thanks for the issue.

It doesn't make sense use that `url` parameter, would you use that url for all http methods? One thing, you can use`get`, `post`, `put` and `delete` methods instead using `resources`.
```ruby
post 'relationships', to: "/relationships/:type"
```
IMO I think you should to send that type in the body of the request, that kind of url it has more sense for a get request.

**Comment by jodosha** [comment]
@choallin I'm sorry, but that would complicate the internals of the framework and it's counterintuitive to me.

What about this?

```ruby
resources :tags do
  resources :relationships do
    get "/:type", to: "foo#bar"
  end
end
```

**Comment by choallin** [comment]
I like this way more.
Only question: What urls would this generate in your opinion?

**Comment by jodosha** [comment]
@choallin It should generate `/tags/relationship/:type`, but I haven't tried it manually. Is my assumption wrong?

**Comment by AlfonsoUceda** [comment]
@jodosha it should be:
```ruby
namespace :tags do
  namespace :relationships do
    get "/:type", to: "foo#bar"
  end
end
#                Name Method     Path                           Action
#
#                     GET, HEAD  /tags/relationships/:type      Foo::Bar
```

**Comment by choallin** [comment]
Sorry, I think I didn't make myself clear so you can't understand what I want this feature for.
I wanted this feature to be able to make a jasonapi compliant realtionship creation/querying
So the urls I want are looking more like this:

GET               http://server/tag/1/relationships/users
PATCH           http://server/tag/2/realtionships/posts
POST             http://server/tag/4/relationships/comments
DELETE         http://server/tag133/relationships/author

Also I need all crud operations for my tags ressource. But I think this could be handled in a separate entry in the routes.rb file
Do you understand know why I want this?

**Comment by mereghost** [comment]
@choallin From what I get you won't need endpoints like `tags/1/relationships/users/1`, right?

If that's the case, the whole routes is decoupled from entities (and the ORM) so you could manage to do this like:
```ruby
resources :tags do
  resources :relationships, only: %i(show destroy update create)
end
```
That would generate `/tags/:id/relationships/:relationships/:id`, the trick is: id can be anything and you can handle the params you allow on your `Action` by a simple validator checking if id matches against a white list.

Would that solve your problem?

**Comment by choallin** [comment]
@mereghost That is a great idea! Id is of course not bound to be a number...
