### ISSUE TITLE
Rubocop

### ISSUE THREAD

**Issue by Neodelf** [hanami/router#133]
Hi there!
I am look that `rubocop` not used in this project.
Used settings from `hanami` repository with `--auto-correct` get result is:
```
66 files inspected, 995 offenses detected, 902 offenses corrected
```
It may be worth adding it?

**Comment by jodosha** [comment]
@Neodelf Yes, definitely. We're slowly adding Rubocop to all the Hanami repositories.

There is a reason why some of them were left behind: we expect to rewrite areas of these gems. For instance, after 1.0, Hanami CLI will be rewritten. So it was useless to add Rubocop now.
