### ISSUE TITLE
Migrate from Minitest to RSpec

### ISSUE THREAD

**Issue by jodosha** [hanami/router#144]
A few rules to follow:

  * If you want to work on this, please leave a comment here. We want to avoid many people to work on the same task.

  * We expect this migration to happen within a week from now.

  * Do not change the tests, only migrate from Minitest to RSpec syntax. If not sure, please ask here.

  * Do not remove the old tests, only add the new ones.

  * Make CI build to use RSpec tests.

  * **Target `develop` branch, instead of `master`.**

  * All the tests artefacts like fixtures, goes under `spec/support`.

  * Try to reflect the structure under `lib/`. Eg. `lib/hanami/view.rb` should be tested under `spec/hanami/view_spec.rb`, while `test/rendering_test.rb` should go under `spec/integration/rendering_spec.rb`.

If you want to take inspiration, please have a look at: https://github.com/hanami/mailer/pull/67

**Comment by morrme** [comment]
It is almost a week from when you posted this, are you still seeking help ?

**Comment by jodosha** [comment]
@morrme Yes, we do.

**Comment by jodosha** [comment]
@morrme Are you working on this?

**Comment by morrme** [comment]
@jodosha i am working on /helpers, just going over the files before i PR

**Comment by jodosha** [comment]
@morrme Thanks for the update 👍

**Comment by morrme** [comment]
OK, I have completed the files for this one now as well. I may need some help with the file structure, but in the meantime I will set up the PR to see if any other changes need to be made.

**Comment by morrme** [comment]
I am researching the remaining problems, and I welcome advice: 

--the test cases (generate and recognition) may need to be totally rewritten
--there's a test that uses the "must_be_same_as" matcher that doesn't have a good synonym in RSpec. 
Example here: https://github.com/hanami/router/blob/master/test/routing_test.rb#L102

I have been experimenting with changing the "response" and using an "include" matcher, as well as creating a variable for the request and then testing for specific values (body, status, etc) , but I didn't want to change too much without approval. 

These problems constitute over 100 failures in the build, so solving them will go a long way towards completing this issue.

**Comment by jodosha** [comment]
@morrme 
> the test cases (generate and recognition) may need to be totally rewritten

Why, specifically?

> there's a test that uses the "must_be_same_as" matcher that doesn't have a good synonym in RSpec.

```ruby
expect(a).to be(b)
```

Shouldn't this work? `be` assets for object identity.

**Comment by jodosha** [comment]
@morrme 
> I have been experimenting with changing the "response" and using an "include" matcher, as well as creating a variable for the request and then testing for specific values (body, status, etc) , but I didn't want to change too much without approval.

What's the reason for this change?

**Comment by morrme** [comment]
@jodosha Thanks for your comments. 

The `be` test indeed worked.

I did not have to re-write the test cases, just add a couple of lines. 

And everything passed! :+1:

**Comment by jodosha** [comment]
Implemented by #145
