### ISSUE TITLE
routing based on request body

### ISSUE THREAD

**Issue by Fedcomp** [hanami/router#151]
Is there a way to route based on request body? say i want `{"type":"confirmation"}` to be routed to `Api::Confirmation`, and `{"type":"validation"}` to `Api::CheckValidation`. Of course i can make custom routing action, but i would like it to be in form of:
```ruby
namespace '/api' do
  post :callback,   type: :confirmation, to: 'callback#confirmation'
  post :validation, type: :validation,   to: 'callback#check_validation'
end
```
thoughts?

**Comment by jodosha** [comment]
@Fedcomp I don't think this is something we would consider. It's an edge case, and it requires to parse the HTTP body, before to route the request. This last detail can make the router slow.

**Comment by kaikuchn** [comment]
While you can make the body accessible by [enabling body parsing](https://github.com/hanami/router#body-parsers) (which are disabled by default for performance reasons), it is only accessible in the callable that matches the route. A fancy constraint like the one you suggested is not possible in the underlying [http_router gem](https://github.com/joshbuddy/http_router). At least as far as I know.

Two things you could do:
(1) rewrite the path in a rack middleware to have a `type` variable and match on that
(2) enable body parsing and decide in the callable (e.g., a lambda) for the matched route what to do depending on the body content. E.g. something like this (I did not test this!)

```ruby
Hanami::Router.new(parsers: [:json]) do
  post :callback, to: lambda do |env|
    case env['router.params'][:type]
    when :confirmation then Web::Controllers::Callback::Confirmation.new.call(env)
    when :validation then Web::Controllers::Callback::Validation.new.call(env)
    else
      raise Hanami::Routing::EndpointNotFound
    end
  end
end
```

**Comment by Fedcomp** [comment]
@kaikuchn thanks for the answer!

**Comment by jodosha** [comment]
@kaikuchn Thanks for bringing that extra, custom solution.
