### ISSUE TITLE
Using a variable in a namespace

### ISSUE THREAD

**Issue by malin-as** [hanami/router#152]
Hi,

In order to have some internationalisation support on a project, I decided to give a try to URLs of the form `https://server/en/home` where `en` is the chosen locale for the interface. I played a bit with `namespace`:

```ruby
root to: 'root#detect_locale'

namespace ':locale' do
  get     '/',       to: 'root#index',   as: :root
  get     '/home',   to: 'home#index',   as: :home
end
```

This actually works, but I'm afraid it was not designed for that purpose (and might stop working in a future version), since it's impossible to set a filter on it, and since it breaks the path name generation of `resources`.

What are your thoughts on such a feature? I could give a try at a PR.

**Comment by jodosha** [comment]
@malin-as This looks as a great addition. Please give it a try.

**Comment by AlfonsoUceda** [comment]
@malin-as maybe we don't need to amend namespace, what I think is we can add a new word for that porpuse and the word comes to my mind is `scope`, what do you think?

IMO namespace is designed to other purpose so I prefer to add a new word like `scope` or other name.

**Comment by malin-as** [comment]
@AlfonsoUceda I don't see clearly what the difference would be between them, from the point of view of a Hanami user. The way I see it, `namespace` would become just a special case of `scope`, when there's no variable involved.

Either way, I'm having trouble with the internal plumbing, trying to figure out how hanami-router and http_router interact exactly, and what http_router is compiling for each route, and how to debug that. I'm afraid that's too complicated for me.

**Comment by jodosha** [comment]
@AlfonsoUceda Can you please expand what you mean and what are the differences between _namespace_ and _scope_? Thanks!

**Comment by AlfonsoUceda** [comment]
Just if it makes easier the implementation, _namespace_ will create a namespace in ruby and _scope_ just to work with variables.

**Comment by jodosha** [comment]
@AlfonsoUceda but having `#namespace` to dynamically create a Ruby namespace is a breaking change. Am I missing something?

**Comment by jodosha** [comment]
Closing as stale conversation. Is someone wants to take care of this feature, please reopen this issue.
