### ISSUE TITLE
Implement a new routes inspector

### ISSUE THREAD

**Issue by jodosha** [hanami/router#165]
During the rewriting of `hanami-router` I had to disable router inspector feature because of the tons of spec failures.

Before to release v2.0.0, we must implement a new inspector.

**Comment by davydovanton** [comment]
Also, more ideas. I think it will be cool to get users access to routers AST for creating any inspectors which they want.

Something like:
```
apps
-> web
  -> root
  -> /books
-> admin
  -> root
  -> /books
    -> /books/:id/other
```

And after that anyone can create own inspectors instead existed. WDYT?

**Comment by jodosha** [comment]
@davydovanton The router doesn’t have an AST, it’s just an array of routes that preserves the order of declaration. Because that order is important during the match of the routes (for incoming HTTP reqs), I’d preserve that order for the inspector as well. The AST can’t represent that order, which is useful for troubleshooting.

**Comment by ElMassimo** [comment]
When designing a new inspector, it would be nice to consider what it would take to support generating [`Open Api`](http://spec.openapis.org/oas/v3.0.3) documentation [from the routes](https://jooby.io/modules/openapi/).

Even if implemented as a separate library, a good design for the inspector would really simplify the implementation.

```ruby
class App < Hanami::API
  endpoint {
    summary "Find a pet by ID"
    description "Find a pet by ID or throws a 404"
  }
  get '/pets/:id' do |id|
    json(Pet.find(id))
  end
end
```

[DSL inspiration](https://sorbet.org/docs/quickref).

**Comment by jodosha** [comment]
@ElMassimo That should be part of `hanami-api`, `hanami-router` doesn't have all the information needed to achieve what you requested.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/router/pull/208
