### ISSUE TITLE
http_router dependency generates `warning: URI.unescape is obsolete`

### ISSUE THREAD

**Issue by deepj** [hanami/router#183]
When I run `hanami-router` specs. I'm getting a bunch of the following warning from `http_router`:

```
warning: URI.unescape is obsolete
```

The question is if `hanami-router`would depend on `http_router` since the gem hasn't been updated since 2016.

**Comment by AlfonsoUceda** [comment]
@deepj yep, but `http_router` has been replaced in `hanami-router` v2.0 so we won't have a stale dependency anymore.

**Comment by olivierlacan** [comment]
@AlfonsoUceda It's been over a year and hanami-router 2.0 isn't out of alpha? Any plan to suppress this deprecation warning in a patch release or perhaps any progress on 2.0 RC? 

I'd love to help if there are blockers to reach RC. I've started using hanami-router on bare Rack apps and loving the experience so far.

**Comment by jodosha** [comment]
@olivierlacan Thanks for your interest. I recommend using `hanami-router` `v2.0.0.alpha2`. It's a rewrite from `v2.0.0.alpha1`, with astonishing perf results.

This new alpha powers the new `hanami-api`.

Read more at:

  * https://github.com/hanami/router/pull/199
  * http://hanamirb.org/blog/2020/02/26/introducing-hanami-api/
  * https://twitter.com/jodosha/status/1230767011375902723

If you have questions or concerns, please reach me at any time here, or on Twitter. We can jump in a call if that helps.
