### ISSUE TITLE
Warning: URI.unescape is obsolete

### ISSUE THREAD

**Issue by artjomjuferov** [hanami/router#213]
I have just created a fresh Hanami project.

And getting `/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/http_router-0.11.2/lib/http_router/request.rb:10`

I have seen some topics and solutions for this issue. Is it only happening for my local setup? 

That's my `Gemfile.lock`  https://gist.github.com/artjomjuferov/e0b0071da66a6f1b6d2eaf086dae729e

**Comment by jodosha** [comment]
@artjomjuferov Thanks for bringing it to us. That is due to the fact `hanami-router` 1.x is based on top of `http_router`, which is old.

We already solved this issue for `hanami-router` 2 (see https://github.com/hanami/router/tree/unstable).

**Comment by artjomjuferov** [comment]
@jodosha thanks for the clarification
