### ISSUE TITLE
Nested variables/resources 

### ISSUE THREAD

**Issue by nicrou** [hanami/router#215]
Does version 2.0.0 (alpha5) supports nested resources like the previous version: 

```
  resource 'identity' do
    member do
      get '/avatar'
    end

    collection do
      get '/api_keys'
    end
  end
```

or at least multiple variables constraints i.e.` get "/authors/:author_id/books/:id", to: Action`?

**Comment by cllns** [comment]
1. No, Hanami Router v2.0.0, by itself, does not support resourceful routing anymore. That feature was moved into `hanami/hanami`. See #199.
2. Yes, Hanami Router still supports multiple variables in the route:

```ruby
require 'hanami/router'
require 'rack'
Hanami::Router::VERSION # => "2.0.0.alpha5"
router = Hanami::Router.new do
  get "/authors/:author_id/books/:id", to: ->(env) { 
    [200, {}, [ "Author ID: #{ env["router.params"][:author_id] }, Book ID: #{ env["router.params"][:id] }"]]
  }
end
Rack::Server.start app: router, Port: 2300
```

Then visiting `http://localhost:2300/authors/900/books/123` shows: `Author ID: 900, Book ID: 123`

**Comment by jodosha** [comment]
@nicrou This WILL be implemented in `hanami`, but it isn't part of `hanami-router` anymore.

Having that feature in the past forced `Hanami::Router` to be aware of Hanami conventions, have an internal string inflector, and being able to require/boot files. This complicated a lot the internals of the router, and its boot time.

As of 2.0 the router will be just a router (dispatch incoming HTTP request) to an endpoint. Hanami will provide the full stack experience where you'll be able to use RESTful routing.
