### ISSUE TITLE
Unclear errors with differently named wildcard segments

### ISSUE THREAD

**Issue by Jammjammjamm** [hanami/router#229]
I encountered this issue while upgrading from 1.3.2 to 2.0.0.beta2 in a non-hanami app.

I updated my routing to something like this:
```ruby
scope 'test_sessions' do
  get '/:id', to: ...
  get '/:test_session_id/last_test_run', to: ...
  get '/:test_session_id/results', to: ...
end
```
When running my request specs, I'd get the not very helpful error: `LocalJumpError: break from proc-closure`, with no indication where this error originates from (I did eventually trace the exception to https://github.com/hanami/router/blob/main/lib/hanami/router/node.rb#L49). I eventually figured out that the cause was having wildcard segments with different names in the same part of the path. I think it's reasonable to require wildcard segments in the same part of the path to have the same name, but it would be great if that was checked and helpful error messages were provided when found.

A basic spec which demonstrates this behavior:
```ruby
require 'hanami/router'
require 'active_support'
require 'rack/test'

RSpec.describe 'routing wildcard behavior' do
  include Rack::Test::Methods

  let(:app) do
    Hanami::Router.new do
      scope 'resources' do
        get '/:id', to: ->(env) { [200, {}, ['resources/:id']]}
        get '/:resource_id/subresource', to: ->(env) { [200, {}, ['resources/:resource_id/subresources']]}
      end
    end
  end

  it 'responds to /resources/:id' do
    get '/resources/123'
    expect(last_response.status).to eq(200)
  end
end
```
When running, the error and stack trace are less than helpful:
```
Failures:

  1) routing wildcard behavior responds to /resources/:id
     Failure/Error: get '/resources/123'

     LocalJumpError:
       break from proc-closure
     # ./spec/test_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:126:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:126:in `block (2 levels) in <top (required)>'

Finished in 0.00708 seconds (files took 2.22 seconds to load)
1 example, 1 failure
```
If you update the wildcard route segments to both be `:id`, the spec will pass.

**Comment by jodosha** [comment]
@Jammjammjamm What does this means? Can you please show me the code?
> If you update the wildcard route segments to both be :id, the spec will pass.

**Comment by Jammjammjamm** [comment]
If you change
```
        get '/:id', to: ->(env) { [200, {}, ['resources/:id']]}
        get '/:resource_id/subresource', to: ->(env) { [200, {}, ['resources/:resource_id/subresources']]}
```
to
```
        get '/:id', to: ->(env) { [200, {}, ['resources/:id']]}
        get '/:id/subresource', to: ->(env) { [200, {}, ['resources/:resource_id/subresources']]}
```
it should work.

**Comment by jodosha** [comment]
@Jammjammjamm Could you please check https://github.com/hanami/router/pull/241? I can't reproduce the `LocalJumpError`.

What am I missing?

**Comment by Jammjammjamm** [comment]
I'm not having any luck reproducing it either at the moment. I'm seeing the same behavior as your spec.

**Comment by jodosha** [comment]
@Jammjammjamm Thanks for reporting.
