### ISSUE TITLE
Capture names affects finding nested routes

### ISSUE THREAD

**Issue by twe4ked** [hanami/router#252]
Hey!

I've run into some unexpected (to me) behaviour when finding nested routes with different capture names.

Here's an example that shows the behaviour:

- Define a `GET` route at `/foo/:id`
- Define a `GET` route at `/foo/:foo_id/bar`
- `/foo/:foo_id/bar` 404s
- Define a `GET` route at `/foo/:foo_id` (uncomment the line)
- `/foo/:foo_id/bar` now returns 200

```ruby
require "hanami/router"

# gem "hanami-router", "2.0.2"

router = Hanami::Router.new do
  # get "/foo/:foo_id", to: ->(env) { [200, {}, ["/foo/:foo_id #{ env["router.params"] }"]] }
  get "/foo/:id", to: ->(env) { [200, {}, ["/foo/:id #{ env["router.params"] }"]] }
  get "/foo/:foo_id/bar", to: ->(env) { [200, {}, ["/foo/:foo_id/bar #{ env["router.params"] }"]] }
end

req = ->(path) {
  puts "Requesting #{path}"
  response = router.call(
    "REQUEST_METHOD" => "GET",
    "PATH_INFO" => path,
    "SCRIPT_NAME" => "something",
  )
  puts "\tStatus #{response[0]}"
}

req.("/foo/123") # => 200
req.("/foo/123/bar") # => 400
```

Is this behaviour expected?

Extra context: We're using [openapi_first](https://github.com/ahx/openapi_first) which automatically generates a hanami-router based off the OpenAPI definition. Internally it converts the OpenAPI path names like this: `/foo/{bar}/baz` -> `/foo/:bar/baz` and uses those to generate the routes. For now we're going to ensure all our OpenAPI paths use common capture names. We could also look at patching `openapi_first` to ensure the names match across nested routes.

Thanks :)

**Comment by jodosha** [comment]
@twe4ked That is because `get "/foo/:id"` is shadowing `get "/foo/:foo_id/bar"`.

I suggest two alternative approaches:

  1. Reintroduce the commented route `get "/foo/:foo_id"`.
  2. Change the order to have `get "/foo/:foo_id/bar"` first

**Comment by twe4ked** [comment]
Thanks for the help, Luca. 🙏
