### ISSUE TITLE
Catch-all has higher priority than mount

### ISSUE THREAD

**Issue by kukicola** [hanami/router#253]
Hello!
I have noticed that catch-all route has a higher priority than mounted routes. Here is my router:
https://github.com/kukicola/shiny_gems/blob/main/config/routes.rb

So there is sidekiq mounted at the top and catch-all at the bottom. The problem is that `/sidekiq` resolves to catch-all route instead of mounted sidekiq. ( You can test it by visiting https://shinygems.dev/sidekiq )

I think that problem is here: https://github.com/hanami/router/blob/main/lib/hanami/router.rb#L793

I noticed that when using standalone router it's easy to implement custom 404 handling (just by passing proc to initializer) but I couldn't find a way how to do it in the full hanami app, that's why I'm using catch-all route.

**Comment by jodosha** [comment]
@kukicola Hey, thanks for reporting the issue and indicating how to fix it.

Please test the fix in this PR: #254.
If it works, I'll merge it.

Thanks 🙏

**Comment by kukicola** [comment]
@jodosha it works, thank you!
