### ISSUE TITLE
Leading slashes not kept for mounted Rack apps

### ISSUE THREAD

**Issue by pat** [hanami/router#261]
Hi folks

I need to debug this properly, but I'm a bit short on time this week. Figure it's worth flagging nonetheless in case it's something worth investigating prior to the 2.1.0 release.

I have an app with several slices - one of which is mounted at the root, and within that slice there's a Roda app mounted at the root as well (eventually to be migrated to proper Hanami routes/actions, but it's a big migration, so I'd like to take a piecemeal approach).

The leading slash in PATH_INFO is not being passed through to the Roda app - e.g. a URL of `example.com/foo/bar` comes through as `foo/bar` rather than `/foo/bar`. This makes Roda's routing fail.

I've put in place a middleware (to the Roda app) that adds the slash back in, but I figure this could be an issue others face as well? (I'm also debugging another slice that's not being routed to either - unsure if it's the same issue thus far) - I would expect a mounted app to _just work_ - and if Roda expects that slash, perhaps other Rack libraries/apps do as well.

MRI 3.2.2, Hanami 2.1.0.rc2, macOS Sonoma

**Comment by timriley** [comment]
Fixed by #263.

**Comment by timriley** [comment]
Fixed by #263.
