### ISSUE TITLE
double slashes in routes when testing with capybara

### ISSUE THREAD

**Issue by sebastjan-hribar** [hanami/router#88]
Hi,

Since I've upgraded from Lotus 0.5.0 to Hanami 0.7.0 I'm getting the failure below for my feature tests:

```
Expected: "/customers/4/edit"
  Actual: "//customers/4/edit"
```

I haven't changed my tests, I have the same routes setup and under Lotus 0.5.0 I still don't get these failures.

This is the feature test I have:
```
it 'updates customer data' do
    create_action.call(create_params)
    create_action.customer.id.wont_be_nil
    visit "/customers/#{customer_id}/edit"
    current_path.must_equal("/customers/#{customer_id}/edit")

    fill_in('customer[vat_id]', with: var)
    click_button('Update customer')
    current_path.must_equal("/customers/#{customer_id}")
    assert page.has_content?(var), "The updated customer vat id should be #{var}."
  end
```
Here are my routes:

```
resources :projects
resources :persons
resources :languages
resources :customers
resources :services
get '/', to: 'home#index', as: :home
get '/configuration', to: 'configuration#index', as: :configuration
```

The current_path from the above block as printed in the terminal is
```
 //customers/38/edit.
```
When I go through the app manually and update some data, everything works. I'm going through the code if I've missed something when upgrading, but I can't find anything.

regards,
Seba

**Comment by davydovanton** [comment]
@sebastjan-hribar hello!
I can reproduce this bug on my hanami project too (in gemfile -> `lotusrb (0.6.0)`)
