### ISSUE TITLE
Documention/Implementation of handling router errors

### ISSUE THREAD

**Issue by thomas07vt** [hanami/router#96]
Hi, I am trying to user your router in a stand alone app (without the Hanami framework) and I am wondering if there is any documentation around how to handle errors before the request gets to a controller. For instance, how should I handle parsing errors?

Lets say I have this router implementation:
```ruby
$router = Hanami::Router.new(parsers: [:json]) do
  patch '/books', to: ->(env) { [200, {},[env['router.params'].inspect]] }
end
```

And in my config.ru I have something like this:

```ruby
map "/" do
  run $router
end
```

If I pass invalid JSON to /books, a Hanami::Routing::Parsing::BodyParsingError will be raised. But, if I want to handle that in a custom way, how would I implement that?

**Comment by jodosha** [comment]
@thomas07vt Hey, thanks for the question.

What about this?

```ruby
# config.ru
require 'bundler/setup'
require 'hanami/router'

class RackExceptionHandler
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env)
  rescue Hanami::Routing::Parsing::BodyParsingError
    # do something here
  end
end

router = Hanami::Router.new(parsers: [:json]) do
  patch '/books', to: ->(env) { [200, {},[env['router.params'].inspect]] }
end

map "/" do
  use RackExceptionHandler
  run router
end
```

There are a few gems that follow this approach. On top of my mind: `rack-rescue` and `rack-robustness` 

---

If you're using `hanami-router` in combination with `hanami-controller` (read more at [JSON API Apps With Lotus](https://lucaguidi.com/2015/11/24/json-api-apps-with-lotus.html)), you can leverage `Hanami::Action` [exception handling](https://github.com/hanami/controller#exceptions-management).

PS: [Hanami was formerly known as Lotus](http://hanamirb.org/blog/2016/01/22/lotus-is-now-hanami.html)
